### ISSUE TITLE
[bug]Could not parse internal loot modifiers

### ISSUE THREAD

**Issue by khjxiaogu** [Noobulus/Tetra-Pak#12]
Could not parse loot modifier scorching and reaping and cause an exception, is this right?
```
[Server thread/ERROR] [net.minecraftforge.common.loot.LootModifierManager/]: Couldn't parse loot modifier tetrapak:scorching
java.lang.NullPointerException: null
	at net.minecraftforge.common.loot.LootModifierManager.deserializeModifier(LootModifierManager.java:139) ~[forge:?]
	at net.minecraftforge.common.loot.LootModifierManager.lambda$apply$0(LootModifierManager.java:115) ~[forge:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at net.minecraftforge.common.loot.LootModifierManager.apply(LootModifierManager.java:113) ~[forge:?]
	at net.minecraftforge.common.loot.LootModifierManager.func_212853_a_(LootModifierManager.java:54) ~[forge:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	... more
[Server thread/ERROR] [net.minecraftforge.common.loot.LootModifierManager/]: Couldn't parse loot modifier tetrapak:reaping
java.lang.NullPointerException: null
	at net.minecraftforge.common.loot.LootModifierManager.deserializeModifier(LootModifierManager.java:139) ~[forge:?]
	at net.minecraftforge.common.loot.LootModifierManager.lambda$apply$0(LootModifierManager.java:115) ~[forge:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at net.minecraftforge.common.loot.LootModifierManager.apply(LootModifierManager.java:113) ~[forge:?]
	at net.minecraftforge.common.loot.LootModifierManager.func_212853_a_(LootModifierManager.java:54) ~[forge:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
       ... more
```

**Comment by Noobulus** [comment]
Is this bug still present on 1.16?
